/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import Config.passwordHasher;
import Home.Login;
import config.dbConnector;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.regexp.joni.Config;

/**
 *
 * @author just4
 */
public class Register_user extends javax.swing.JFrame {

    /**
     * Creates new form Register_user
     */
    public Register_user() {
        setUndecorated(true);
        initComponents();
    }
    public String question = "";
    public String answer = "";
    public String destination = "";
    public static String Em, username;

    public boolean duplicateCheck() {
        dbConnector dbc = new dbConnector();

        try {
            String query = "SELECT * FROM register WHERE Username = '" + user.getText() + "' OR Email = '" + email.getText() + "'";
            ResultSet resultSet = dbc.getData(query);

            if (resultSet.next()) {
                Em = resultSet.getString("Email");
                if (Em.equals(email.getText())) {
                    JOptionPane.showMessageDialog(null, "Email is Already Used!");
                    email.setText("");
                }

                username = resultSet.getString("Username");
                if (username.equals(user.getText())) {
                    JOptionPane.showMessageDialog(null, "Username is Already Used!");
                    user.setText("");
                }
                return true;
            } else {
                return false;
            }

        } catch (SQLException ex) {
            System.out.println("" + ex);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        design = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pass2 = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        surname = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        post = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        department = new javax.swing.JTextField();
        job = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        add1 = new javax.swing.JTextField();
        add2 = new javax.swing.JTextField();
        hnum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTER");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Surname :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        design.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Role", "Teacher", "HR", "HRAssistant" }));
        design.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designActionPerformed(evt);
            }
        });
        getContentPane().add(design, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 150, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date of Birth :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gender:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Username :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address Line 1 :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address Line 2 :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 160, 60));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Apt./House No :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Verify Password :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass2ActionPerformed(evt);
            }
        });
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 150, -1));
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 150, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Post Code :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Department :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Designation :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Job Title :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 100, 50, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Male", "Female" }));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 150, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/USER/Image/erase-128.png"))); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 160, 60));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/USER/Image/bk3.jpg"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 80, 150));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/USER/Image/Staff.png"))); // NOI18N
        jButton3.setText("REGISTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 160, 60));

        surname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 150, -1));

        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, -1));

        post.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 150, -1));

        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, -1));

        department.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 150, -1));

        job.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(job, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 150, -1));

        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 150, -1));

        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, -1));

        add1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 150, -1));

        add2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 150, -1));

        hnum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(hnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/USER/Image/bk3.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void designActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String firstName = fname.getText().trim();
        String Surname = surname.getText().trim();
        String Date = date.getText().trim();
        String address1 = add1.getText().trim();
        String address2 = add2.getText().trim();
        String Housenum = hnum.getText().trim();
        String contactNumber = contact.getText().trim();
        String postcode = post.getText().trim();
        String emailText = email.getText().trim();
        String Department = department.getText().trim();
        String jobtitle = job.getText().trim();
        String password = pass1.getText().trim();
        String password2 = pass2.getText().trim();
        String username = user.getText().trim();
        if (firstName.isEmpty() || gender.getSelectedIndex() == 0 || design.getSelectedIndex() == 0 
                || address1.isEmpty() || address2.isEmpty() || contactNumber.isEmpty() || emailText.isEmpty() || Housenum.isEmpty()
                || Date.isEmpty()|| postcode.isEmpty()|| Department.isEmpty()|| jobtitle.isEmpty()
               || password.isEmpty() || password2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
        } else if (password.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long.");
        } else if (!password.equals(password2)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match.");
        } else if (!contactNumber.matches("\\d{10,15}")) {
            JOptionPane.showMessageDialog(null, "Contact number must contain only numbers and be between 10-15 digits.");
        }else if (!Housenum.matches("\\d{1,15}")) {
            JOptionPane.showMessageDialog(null, "Apt/House number must contain only numbers.");
        }else if (!postcode.matches("\\d{1,15}")) {
            JOptionPane.showMessageDialog(null, "Postcode number must contain only numbers.");
        }else if (!emailText.matches("^.+@.+\\..+$")) {
            JOptionPane.showMessageDialog(null, "Invalid email format.");
        } else if (duplicateCheck()) {
            System.out.println("DUPLICATE EXIST");
        } else {
            try{
                dbConnector dbc = new dbConnector();
                String pass = passwordHasher.hashPassword(pass1.getText());
                
                if (dbc.insertData("INSERT INTO register (fname, surname, `date`, gender, Username, Email, Contact, address1, address2, Hnum, post, department, designation, jobtitle, password, Status, question, answer, image) " 
                + "VALUES ('" + firstName + "', '" + Surname + "', '" + Date + "', '"
                + gender.getSelectedItem().toString() + "', '" + username + "', '" + emailText + "', '" + contactNumber + "', '" + address1 + "', "
                + "'" + address2 + "', '" + Housenum + "', '" + postcode + "', '" + Department + "', '" + design.getSelectedItem().toString() + "', '"
                + jobtitle + "', '" + pass + "', 'Pending', '"+question+"', '"+answer+"', '"+destination+"')") == 1) {

            JOptionPane.showMessageDialog(null, "Successfully Registered");
            Login Log = new Login();
            Log.setVisible(true);
            this.dispose();
            }
            }catch(NoSuchAlgorithmException ex){
                System.out.println(""+ex);
            }           
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fname.setText("");
       surname.setText("");
       date.setText("");
       add1.setText("");
       add2.setText("");
       hnum.setText("");
       contact.setText("");
       post.setText("");
       email.setText("");
       department.setText("");
       job.setText("");
       pass1.setText("");
       gender.setSelectedIndex(0);
       pass2.setText("");
       user.setText("");
       design.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add1;
    private javax.swing.JTextField add2;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField date;
    private javax.swing.JTextField department;
    private javax.swing.JComboBox<String> design;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField hnum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField job;
    private javax.swing.JTextField pass1;
    private javax.swing.JTextField pass2;
    private javax.swing.JTextField post;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
