/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import config.dbConnector;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author II
 */
public class attendance extends javax.swing.JFrame {

    /**
     * Creates new form attendance
     */
    public attendance() {
        setUndecorated(true);
        initComponents();
        loadEmployeesToComboBox();
        loadAttendanceTable();
    }
    private void loadEmployeesToComboBox() {
    userCombo.removeAllItems(); 

    String sql = "SELECT id, fname, surname FROM register";

    try {
        dbConnector db = new dbConnector();
        ResultSet rs = db.getData(sql);

        while (rs.next()) {
            int id = rs.getInt("id");
            String fullName = rs.getString("fname") + " " + rs.getString("surname");
            userCombo.addItem(id + " - " + fullName);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void loadAttendanceTable() { 
    String[] headers = {"ID", "Employee Name", "Date", "Time In", "Time Out", "Status"};
    DefaultTableModel model = new DefaultTableModel(headers, 0);
    attendanceTable.setModel(model);

    String sql = "SELECT a.id, r.fname, r.surname, a.date, a.time_in, a.time_out, a.status " +
                 "FROM attendance a JOIN register r ON a.employee_id = r.id";

    try {
        dbConnector db = new dbConnector(); // Use your db helper
        ResultSet rs = db.getData(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("fname") + " " + rs.getString("surname"),
                rs.getString("date"),
                rs.getString("time_in"),
                rs.getString("time_out"),
                rs.getString("status")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        userCombo = new javax.swing.JComboBox<>();
        attendancedate = new com.toedter.calendar.JDateChooser();
        Timeout = new javax.swing.JTextField();
        Status = new javax.swing.JComboBox<>();
        RecordAttendance = new javax.swing.JButton();
        Timein = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ATTENDANCE - HR");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 480, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 91));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendanceTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        attendanceTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(attendanceTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 440));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 102, 540, 460));

        userCombo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboActionPerformed(evt);
            }
        });
        jPanel1.add(userCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, 50));
        jPanel1.add(attendancedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, -1));

        Timeout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Timeout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Timeout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 50));

        Status.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Present", "Late", "Absent" }));
        Status.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 160, 50));

        RecordAttendance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RecordAttendance.setText("Record Attendance");
        RecordAttendance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RecordAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordAttendanceActionPerformed(evt);
            }
        });
        jPanel1.add(RecordAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 190, 40));

        Timein.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Timein.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Timein, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 160, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Status:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Time IN:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Time OUT:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Employee:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userComboActionPerformed

    private void RecordAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordAttendanceActionPerformed
           String selectedUser = userCombo.getSelectedItem().toString();
    int employeeId = Integer.parseInt(selectedUser.split(" - ")[0]);
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String date = sdf.format(attendancedate.getDate());
   String timeInInput = Timein.getText().trim();
String timeOutInput = Timeout.getText().trim();

SimpleDateFormat inputFormat = new SimpleDateFormat("h:mm a"); // e.g. 7:00 AM
SimpleDateFormat outputFormat = new SimpleDateFormat("HH:mm:ss"); // 24-hour format for MySQL TIME

String timeIn = "";
String timeOut = "";

try {
    Date parsedTimeIn = inputFormat.parse(timeInInput);
    timeIn = outputFormat.format(parsedTimeIn);

    Date parsedTimeOut = inputFormat.parse(timeOutInput);
    timeOut = outputFormat.format(parsedTimeOut);
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Invalid time format. Use like 7:00 AM", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
    String status = Status.getSelectedItem().toString();

    if (date.isEmpty() || timeIn.isEmpty() || timeOut.isEmpty() || status.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String sql = "INSERT INTO attendance (employee_id, date, time_in, time_out, status) " +
                 "VALUES ('" + employeeId + "', '" + date + "', '" + timeIn + "', '" + timeOut + "', '" + status + "')";

    dbConnector db = new dbConnector();
    int result = db.insertData(sql);

    if (result == 1) {
        JOptionPane.showMessageDialog(this, "Attendance recorded successfully!");
        loadAttendanceTable(); // Refresh table if needed
    } else {
        JOptionPane.showMessageDialog(this, "Failed to record attendance.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_RecordAttendanceActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    Admin_dashboard aa = new Admin_dashboard();
    aa.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RecordAttendance;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JTextField Timein;
    private javax.swing.JTextField Timeout;
    private javax.swing.JTable attendanceTable;
    private com.toedter.calendar.JDateChooser attendancedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> userCombo;
    // End of variables declaration//GEN-END:variables
}
