/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import Config.PDFExporter;
import config.dbConnector;
import java.awt.Graphics2D;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author II
 */
public class GeneratePayslipForm extends javax.swing.JFrame {

    /**
     * Creates new form GeneratePayslipForm
     */
    public GeneratePayslipForm() {
        setUndecorated(true);
        initComponents();
         loadEmployeesToCombo();
    }
private void loadEmployeesToCombo() {
    employeeCombo.removeAllItems();
    try {
        dbConnector db = new dbConnector();
        ResultSet rs = db.getData("SELECT id, fname, surname FROM register");

        while (rs.next()) {
            int id = rs.getInt("id");
            String name = rs.getString("fname") + " " + rs.getString("surname");
            employeeCombo.addItem(id + " - " + name);
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        employeeCombo = new javax.swing.JComboBox<>();
        payslipDate = new com.toedter.calendar.JDateChooser();
        generateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        payslipArea = new javax.swing.JTextArea();
        printBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Generate PaySlip - HR");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BACK");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 80));

        employeeCombo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        employeeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employeeCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(employeeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 70));
        jPanel1.add(payslipDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 320, -1));

        generateBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        generateBtn.setText("Generate Payslip");
        generateBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(generateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 203, 170, 30));

        payslipArea.setColumns(20);
        payslipArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        payslipArea.setRows(5);
        payslipArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(payslipArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 286, 730, 280));

        printBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        printBtn.setText("Print Payslip");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        jPanel1.add(printBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 160, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Select Employee:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("PaySlip Date:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
     String selected = (String) employeeCombo.getSelectedItem();
    if (selected == null || selected.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select an employee.");
        return;
    }

    int employeeId = Integer.parseInt(selected.split(" - ")[0]);

    java.util.Date selectedDate = payslipDate.getDate();
    if (selectedDate == null) {
        JOptionPane.showMessageDialog(this, "Please select a payslip date.");
        return;
    }

    String sql = "SELECT r.fname, r.surname, s.salary_date, s.basic_salary, s.allowance, s.deduction, s.total_salary " +
                 "FROM salary s JOIN register r ON s.employee_id = r.id " +
                 "WHERE s.employee_id = ? ORDER BY s.salary_date DESC LIMIT 1";

    try {
        dbConnector db = new dbConnector();
        PreparedStatement pst = db.getConnection().prepareStatement(sql);
        pst.setInt(1, employeeId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // Retrieve and compute values
            String fname = rs.getString("fname");
            String surname = rs.getString("surname");
            Date salaryDate = rs.getDate("salary_date");
            double basic = rs.getDouble("basic_salary");
            double allowance = rs.getDouble("allowance");
            double deduction = rs.getDouble("deduction");
            double net = rs.getDouble("total_salary");
            double gross = basic + allowance;

            LocalDate periodEnd = salaryDate.toLocalDate();
            LocalDate periodStart = periodEnd.minusMonths(1);

            // Check for duplicate payslip
            String checkSql = "SELECT id FROM payslips WHERE employee_id = ? AND period_start = ? AND period_end = ?";
            PreparedStatement checkPst = db.getConnection().prepareStatement(checkSql);
            checkPst.setInt(1, employeeId);
            checkPst.setDate(2, Date.valueOf(periodStart));
            checkPst.setDate(3, Date.valueOf(periodEnd));
            ResultSet checkRs = checkPst.executeQuery();

            if (checkRs.next()) {
                JOptionPane.showMessageDialog(this, "Payslip for this period is already generated.");
                checkRs.close();
                checkPst.close();
                return;
            }

            checkRs.close();
            checkPst.close();

            // Build payslip string
            StringBuilder payslip = new StringBuilder();
            payslip.append("============================== PAYSLIP ======================\n");
            payslip.append("                    Name: ").append(fname).append(" ").append(surname).append("\n");
            payslip.append("                    Date: ").append(salaryDate).append("\n");
            payslip.append("--------------------------------------------------------------\n");
            payslip.append("                    Basic Salary: ₱").append(basic).append("\n");
            payslip.append("                    Allowance:    ₱").append(allowance).append("\n");
            payslip.append("                    Deduction:    ₱").append(deduction).append("\n");
            payslip.append("---------------------------------------------------------------\n");
            payslip.append("                    Total Salary: ₱").append(net).append("\n");
            payslip.append("=============================================================== \n");

            payslipArea.setText(payslip.toString());

            // Insert into payslips table
            String insertSQL = "INSERT INTO payslips (employee_id, period_start, period_end, gross_pay, total_deduct, net_pay) " +
                               "VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement insertPst = db.getConnection().prepareStatement(insertSQL);
            insertPst.setInt(1, employeeId);
            insertPst.setDate(2, Date.valueOf(periodStart));
            insertPst.setDate(3, Date.valueOf(periodEnd));
            insertPst.setDouble(4, gross);
            insertPst.setDouble(5, deduction);
            insertPst.setDouble(6, net);

            int inserted = insertPst.executeUpdate();
            if (inserted > 0) {
                JOptionPane.showMessageDialog(this, "Payslip successfully generated and saved.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save payslip.");
            }

            insertPst.close();
        } else {
            JOptionPane.showMessageDialog(this, "No salary record found for selected employee.");
        }

        rs.close();
        pst.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error generating payslip: " + e.getMessage());
    }
    }//GEN-LAST:event_generateBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
      PDFExporter.exportPayslipFromTextArea(payslipArea);
    }//GEN-LAST:event_printBtnActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Admin_dashboard aa = new Admin_dashboard();
       aa.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslipForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslipForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslipForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslipForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratePayslipForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> employeeCombo;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea payslipArea;
    private com.toedter.calendar.JDateChooser payslipDate;
    private javax.swing.JButton printBtn;
    // End of variables declaration//GEN-END:variables
}
