/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author II
 */
public class SalaryForm extends javax.swing.JFrame {

    /**
     * Creates new form SalaryForm
     */
    public SalaryForm() {
        setUndecorated(true);
        initComponents();
        loadEmployeesToComboBox();
        loadSalaryTable();
    }
  private void loadEmployeesToComboBox() {
    userCombo.removeAllItems(); // Clear previous items

    String sql = "SELECT id, fname, surname FROM register";

    try {
        dbConnector db = new dbConnector();
        ResultSet rs = db.getData(sql);

        while (rs.next()) {
            int id = rs.getInt("id");
            String fullName = rs.getString("fname") + " " + rs.getString("surname");
            userCombo.addItem(id + " - " + fullName);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
  private void loadSalaryTable() {
    DefaultTableModel model = (DefaultTableModel) salaryTable.getModel();
    model.setRowCount(0); // Clear existing rows

    
    if (model.getColumnCount() == 0) {
        model.setColumnIdentifiers(new Object[]{
            "ID", "Employee Name", "Basic Salary", "Allowance", "Deduction", "Total Salary", "Salary Date"
        });
    }

    String sql = "SELECT s.id, r.fname, r.surname, s.basic_salary, s.allowance, s.deduction, s.total_salary, s.salary_date " +
                 "FROM salary s JOIN register r ON s.employee_id = r.id ORDER BY s.salary_date DESC";

    try {
        dbConnector db = new dbConnector();
        ResultSet rs = db.getData(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("fname") + " " + rs.getString("surname"),
                rs.getDouble("basic_salary"),
                rs.getDouble("allowance"),
                rs.getDouble("deduction"),
                rs.getDouble("total_salary"),
                rs.getDate("salary_date")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading salary records: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userCombo = new javax.swing.JComboBox<>();
        totalSalaryField = new javax.swing.JTextField();
        basicSalaryField = new javax.swing.JTextField();
        allowanceField = new javax.swing.JTextField();
        deductionField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salaryTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Salary Form -HR");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BACK");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        userCombo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(userCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, 50));

        totalSalaryField.setEditable(false);
        totalSalaryField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        totalSalaryField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(totalSalaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 170, 60));

        basicSalaryField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        basicSalaryField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(basicSalaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 170, 60));

        allowanceField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        allowanceField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(allowanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 170, 60));

        deductionField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deductionField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(deductionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 170, 60));

        calculateButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(calculateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 110, 40));

        saveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 100, 50));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        salaryTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Employee Name", "Basic Salary", "Allowance", "Deduction", "Total Salary", "Salary Date"
            }
        ));
        jScrollPane1.setViewportView(salaryTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 530, 90));

        jLabel2.setText("Salaries:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Basic Salary:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 214, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Allowance:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Deductions:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Total Salary:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Select Employee:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Standard deduction:\nSSS: ₱375.00\nPhilHealth: ₱187.50\nPag-IBIG: ₱150.00\nLate: 250.00\nAbsent: 750.00\n");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
      try {
        double basic = Double.parseDouble(basicSalaryField.getText());
        double allowance = Double.parseDouble(allowanceField.getText());
        double deduction = Double.parseDouble(deductionField.getText());

        double total = basic + allowance - deduction;
        totalSalaryField.setText(String.format("%.2f", total));
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    String selectedUser = userCombo.getSelectedItem().toString();
    int employeeId = Integer.parseInt(selectedUser.split(" - ")[0]);

    String basicSalary = basicSalaryField.getText();
    String allowance = allowanceField.getText();
    String deduction = deductionField.getText();
    String totalSalary = totalSalaryField.getText();

    // You can add a date picker or use current date
    String salaryDate = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

    if (basicSalary.isEmpty() || allowance.isEmpty() || deduction.isEmpty() || totalSalary.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fill in all fields", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String sql = "INSERT INTO salary (employee_id, basic_salary, allowance, deduction, total_salary, salary_date) " +
                 "VALUES ('" + employeeId + "', '" + basicSalary + "', '" + allowance + "', '" + deduction + "', '" + totalSalary + "', '" + salaryDate + "')";

    dbConnector db = new dbConnector();
    int result = db.insertData(sql);

    if (result == 1) {
        JOptionPane.showMessageDialog(this, "Salary saved successfully!");
        // Reload salary table or clear fields if needed
    } else {
        JOptionPane.showMessageDialog(this, "Failed to save salary.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Admin_dashboard aa = new Admin_dashboard();
       aa.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField allowanceField;
    private javax.swing.JTextField basicSalaryField;
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField deductionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable salaryTable;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField totalSalaryField;
    private javax.swing.JComboBox<String> userCombo;
    // End of variables declaration//GEN-END:variables
}
