/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import config.dbConnector;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author II
 */
public class ViewPayslip extends javax.swing.JFrame {

    /**
     * Creates new form ViewPayslip
     */
    public ViewPayslip() {
        setUndecorated(true);
        initComponents();
        loadPayslip();
        loadEmployeeCombo();
        
    }
    private void loadEmployeeCombo() {
    try {
        dbConnector db = new dbConnector();
        String sql = "SELECT id, fname, surname FROM register";
        ResultSet rs = db.getData(sql);
        employeeCombo.removeAllItems();

        while (rs.next()) {
            int id = rs.getInt("id");
            String name = rs.getString("fname") + " " + rs.getString("surname");
            employeeCombo.addItem(id + " - " + name);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void loadPayslip() {
    String selected = (String) employeeCombo.getSelectedItem();
    if (selected == null || selected.isEmpty()) return;

    int employeeId = Integer.parseInt(selected.split(" - ")[0]);
    java.util.Date selectedDate = payslipDate.getDate();
    if (selectedDate == null) {
        JOptionPane.showMessageDialog(this, "Please select a date.");
        return;
    }

    java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());

    String sql = "SELECT r.fname, r.surname, s.* FROM salary s JOIN register r ON s.employee_id = r.id " +
                 "WHERE s.employee_id = ? AND s.salary_date = ?";

    try {
        dbConnector db = new dbConnector();
        PreparedStatement pst = db.getConnection().prepareStatement(sql);
        pst.setInt(1, employeeId);
        pst.setDate(2, sqlDate);

        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            StringBuilder payslip = new StringBuilder();
            payslip.append("======= PAYSLIP =======\n");
            payslip.append("Name: ").append(rs.getString("fname")).append(" ").append(rs.getString("surname")).append("\n");
            payslip.append("Date: ").append(rs.getDate("salary_date")).append("\n");
            payslip.append("------------------------\n");
            payslip.append("Basic Salary: ₱").append(rs.getDouble("basic_salary")).append("\n");
            payslip.append("Allowance:    ₱").append(rs.getDouble("allowance")).append("\n");
            payslip.append("Deduction:    ₱").append(rs.getDouble("deduction")).append("\n");
            payslip.append("------------------------\n");
            payslip.append("Total Salary: ₱").append(rs.getDouble("total_salary")).append("\n");
            payslip.append("========================\n");

            payslipArea.setText(payslip.toString());
        } else {
            JOptionPane.showMessageDialog(this, "No payslip found for this employee and date.");
            payslipArea.setText("");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading payslip: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        employeeCombo = new javax.swing.JComboBox<>();
        payslipDate = new com.toedter.calendar.JDateChooser();
        viewBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        payslipArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 246, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Payslip - HR");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(241, 241, 241))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 70));

        employeeCombo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        employeeCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(employeeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 290, 50));
        jPanel1.add(payslipDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 330, -1));

        viewBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewBtn.setText("View Payslip");
        viewBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 173, 150, 40));

        payslipArea.setColumns(20);
        payslipArea.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        payslipArea.setRows(5);
        jScrollPane1.setViewportView(payslipArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 226, 800, 310));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Payslip generated:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Employee:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Date:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
       loadPayslip();
    }//GEN-LAST:event_viewBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       Admin_dashboard aa = new Admin_dashboard();
       aa.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPayslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> employeeCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea payslipArea;
    private com.toedter.calendar.JDateChooser payslipDate;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
